kernel:
  image: linuxkit/kernel:4.14.58
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:598439400c1e4bf8c25c63c98b2d3e83b1382be9
  - linuxkit/runc:v0.5
  - linuxkit/containerd:0784cc754edb296b996c3510abbdf69686ef0f24
  - linuxkit/ca-certificates:v0.5
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.5
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.5
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:721562e6f3ba9b6c003f9e746ff7ee94796f5251
services:
  - name: getty
    image: linuxkit/getty:v0.5
    env:
      - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.5
  - name: helpdesk
    image: adampointer83/go-helpdesk:master
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
    net: host
    env:
      - HELP_SIGNING_SECRET="xxxyyyzzz"
      - HELP_BOT_TOKEN="xxxyyyzzz"
      - HELP_APP_TOKEN="xxxyyyzzz"
      - HELP_LISTEN_ADDRESS="0.0.0.0:4390"
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
trust:
  org:
    - linuxkit
    - library
